// Generated by CodiumAI

describe('activate', () => {

});

    // Test that a button is created in the current window
    it('should create a button in the current window', () => {
      // Mock the vscode.window.createStatusBarItem method
      const createStatusBarItemMock = jest.spyOn(vscode.window, 'createStatusBarItem');
  
      // Call the activate function
      activate(vscode.ExtensionContext);
  
      // Expect the createStatusBarItem method to be called with the correct arguments
      expect(createStatusBarItemMock).toHaveBeenCalledWith(vscode.StatusBarAlignment.Left);
      expect(createStatusBarItemMock.mock.calls[0][0].text).toBe('Rajaji is here');
      expect(createStatusBarItemMock.mock.calls[0][0].command).toBe('duplicatechecker.helloWorld');
  
      // Restore the mock
      createStatusBarItemMock.mockRestore();
    });

